/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.4.1.1                                               */
/*  Date (dd.mm.yyyy): 13. 3.2019   Time (hh:mm): 22:08                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define DISPLAY_1_COLOR_TABLE_SIZE 25

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define GX_PIXELMAP_ID_BACKBUTTON 5
#define GX_PIXELMAP_ID_BLACKUPARROW 6
#define GX_PIXELMAP_ID_GRAY_STATUS 7
#define GX_PIXELMAP_ID_GREEN_STATUS 8
#define GX_PIXELMAP_ID_ICON_CREDITS_WINDOW 9
#define GX_PIXELMAP_ID_ICON_MORE5 10
#define GX_PIXELMAP_ID_ICON_SETTING_WINDOW 11
#define GX_PIXELMAP_ID_MENU2 12
#define GX_PIXELMAP_ID_P_CREDITS_SCREEN 13
#define GX_PIXELMAP_ID_P_MAINPAGE_ 14
#define GX_PIXELMAP_ID_P_MAINPAGE_V2 15
#define GX_PIXELMAP_ID_P_MAIN_SCREEN 16
#define GX_PIXELMAP_ID_RED_STATUS 17
#define GX_PIXELMAP_ID_REFRESH 18
#define GX_PIXELMAP_ID_RES7 19
#define GX_PIXELMAP_ID_WINDOW3 20
#define GX_PIXELMAP_ID_WINDOW5 21
#define GX_PIXELMAP_ID_WINDOW6 22
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 23

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_ONE 4
#define GX_STRING_ID_STRING_4 5
#define GX_STRING_ID_STRING_5 6
#define GX_STRING_ID_STRING_6 7
#define GX_STRING_ID_STRING_7 8
#define GX_STRING_ID_TWO 9
#define GX_STRING_ID_STRING_8 10
#define GX_STRING_ID_THREE 11
#define GX_STRING_ID_STRING_9 12
#define GX_STRING_ID_STRING_10 13
#define GX_STRING_ID_STRING_11 14
#define GX_STRING_ID_MON1 15
#define GX_STRING_ID_MON2 16
#define GX_STRING_ID_MON3 17
#define GX_STRING_ID_MON4 18
#define GX_STRING_ID_MON5 19
#define GX_STRING_ID_MON6 20
#define GX_STRING_ID_MON7 21
#define GX_STRING_ID_MON8 22
#define GX_STRING_ID_MON9 23
#define GX_STRING_ID_MON10 24
#define GX_STRING_ID_MON11 25
#define GX_STRING_ID_MON12 26
#define GX_STRING_ID_STRING_12 27
#define GX_STRING_ID_DAY1 28
#define GX_STRING_ID_DAY2 29
#define GX_STRING_ID_DAY3 30
#define GX_STRING_ID_DAY4 31
#define GX_STRING_ID_DAY5 32
#define GX_STRING_ID_DAY6 33
#define GX_STRING_ID_DAY7 34
#define GX_STRING_ID_YEAR1 35
#define GX_STRING_ID_YEAR2 36
#define GX_STRING_ID_YEAR3 37
#define GX_STRING_ID_FOUR 38
#define GX_STRING_ID_FIVE 39
#define GX_STRING_ID_SIX 40
#define GX_STRING_ID_SEVEN 41
#define GX_STRING_ID_EIGHT 42
#define GX_STRING_ID_NINE 43
#define GX_STRING_ID_ZERO 44
#define GX_STRING_ID_STATUS_ON 45
#define GX_STRING_ID_NO_STATUS 46
#define GX_STRING_ID_STATUS_OFF 47
#define GX_STRING_ID_STRING_13 48
#define DISPLAY_1_STRING_TABLE_SIZE 49

#endif                                       /* sentry                         */
